openapi: 3.0.0
info:
  title: API de Viagem Espacial
  description: API para planejar e vivenciar viagens espaciais virtuais.
  version: "1.0.0"

servers:
  - url: http://localhost:3000
    description: Servidor de Desenvolvimento

paths:
  /destinos:
    get:
      summary: Lista todos os destinos espaciais
      responses:
        '200':
          description: Uma lista de destinos espaciais
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destino'

  /destinos/{id}:
    get:
      summary: Obtém um destino espacial pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do destino espacial
      responses:
        '200':
          description: Detalhes de um destino espacial
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destino'
        '404':
          description: Destino não encontrado

components:
  schemas:
    Destino:
      type: object
      required:
        - id
        - nome
        - tipo
        - descricao
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: Marte
        tipo:
          type: string
          example: Planeta
        descricao:
          type: string
          example: O quarto planeta do sistema solar.
